<?php

namespace Database\Seeders;

use App\Models\Epreuve;
use Illuminate\Database\Seeder;

/**
 * Premier lot de questions de compréhension écrite (documents fictifs), de A1-bas à C2-haut : deux questions par sous-niveau.
 * Les documents s'allongent avec le niveau : 10 à 50 mots en A1, 40 à 100 en A2, 80 à 160 en B1, 140 à 230 en B2, 200 à 290 en C1, 250 à 350 en C2.
 * Relancer ce seeder remplace les questions de l'épreuve qui ont un niveau, sans toucher aux autres.
 */
class ComprehensionEcriteSeeder extends Seeder
{
    public function run(): void
    {
        $this->questions([
            [
                'niveau' => 'A1',
                'sous_niveau' => 'bas',
                'categorie' => 'Annonces et affiches',
                'enonce' => 'Quel jour la boulangerie est-elle fermée ?',
                'support' => "Boulangerie Dumont – Namur\nFermée le lundi\nDu mardi au samedi : de 7 h à 18 h\nLe dimanche : de 7 h à 12 h",
                'choix' => ['Le dimanche', 'Le mardi', 'Le lundi', 'Le samedi'],
                'bonne_reponse' => 2,
                'feedback' => 'Bravo, tu as trouvé le jour de fermeture !',
                'explication' => "L'affiche indique « Fermée le lundi ». Du mardi au samedi, la boulangerie est ouverte de 7 h à 18 h. Le dimanche, elle ouvre aussi, mais seulement le matin : « de 7 h à 12 h ».",
            ],
            [
                'niveau' => 'A1',
                'sous_niveau' => 'bas',
                'categorie' => 'Vie quotidienne',
                'enonce' => 'Combien coûte le yassa poulet ?',
                'support' => "Chez Awa – Dakar\nThiéboudienne : 2 500 F CFA\nYassa poulet : 2 000 F CFA\nMafé : 1 500 F CFA\nJus de bissap : 500 F CFA",
                'choix' => ['2 000 F CFA', '2 500 F CFA', '1 500 F CFA', '500 F CFA'],
                'bonne_reponse' => 0,
                'feedback' => 'Bien lu, tu as trouvé la bonne ligne du menu !',
                'explication' => "Le menu indique « Yassa poulet : 2 000 F CFA ». Les autres prix correspondent à d'autres lignes : 2 500 F CFA pour le thiéboudienne, 1 500 F CFA pour le mafé et 500 F CFA pour le jus de bissap.",
            ],
            [
                'niveau' => 'A1',
                'sous_niveau' => 'moyen',
                'categorie' => 'Messages et courriels',
                'enonce' => 'À quelle heure Chloé propose-t-elle de retrouver Inès ?',
                'support' => "Salut Inès !\nJe finis le travail à 18 h 30. Le film commence à 20 h 15 et finit à 22 h 30. On se retrouve devant le cinéma à 19 h 30 ? Après, on va manger une pizza !\nChloé",
                'choix' => ['À 18 h 30', 'À 19 h 30', 'À 20 h 15', 'À 22 h 30'],
                'bonne_reponse' => 1,
                'feedback' => "Bien joué, tu n'as pas confondu les différentes heures !",
                'explication' => 'Chloé propose : « On se retrouve devant le cinéma à 19 h 30 ? » Les autres heures correspondent à autre chose : à 18 h 30, Chloé « finit le travail » ; à 20 h 15, le film « commence » ; à 22 h 30, il « finit ».',
            ],
            [
                'niveau' => 'A1',
                'sous_niveau' => 'moyen',
                'categorie' => 'Vie quotidienne',
                'enonce' => "Où est la clé de l'appartement de Paul ?",
                'support' => "Bonjour Madame Favre,\nJe pars en vacances au Tessin du 3 au 17 juillet. Pouvez-vous arroser mes plantes le mardi et le vendredi ? La clé est chez le concierge.\nMerci beaucoup !\nPaul (appartement 12)",
                'choix' => ['Chez Madame Favre', "Dans l'appartement 12", 'Avec Paul, en vacances', 'Chez le concierge'],
                'bonne_reponse' => 3,
                'feedback' => "Parfait, tu as repéré l'information utile !",
                'explication' => "Paul écrit : « La clé est chez le concierge. » Madame Favre ne l'a donc pas encore : elle doit aller la chercher pour arroser les plantes. L'« appartement 12 » est simplement le logement de Paul. Et Paul ne part pas en vacances avec la clé, puisqu'il l'a laissée au concierge.",
            ],
            [
                'niveau' => 'A1',
                'sous_niveau' => 'haut',
                'categorie' => 'Annonces et affiches',
                'enonce' => 'Comment faut-il contacter Julie ?',
                'support' => "À vendre : vélo d'enfant bleu, très bon état, 60 $.\nMon fils a grandi : le vélo est trop petit pour lui.\nIdéal pour un enfant de 6 à 9 ans.\nAppelez Julie après 17 h au 514 555-0142.\nPas de texto, s'il vous plaît.",
                'choix' => ['Par texto, après 17 h', 'Par téléphone, avant 17 h', 'Par texto, avant 17 h', 'Par téléphone, après 17 h'],
                'bonne_reponse' => 3,
                'feedback' => 'Bien vu, tu as fait attention au « Pas de texto » !',
                'explication' => "L'annonce dit : « Appelez Julie après 17 h. » Il faut donc lui téléphoner, et seulement après 17 h : les réponses « avant 17 h » sont fausses. Les réponses « par texto » aussi, car l'annonce précise : « Pas de texto, s'il vous plaît. »",
            ],
            [
                'niveau' => 'A1',
                'sous_niveau' => 'haut',
                'categorie' => 'Messages et courriels',
                'enonce' => 'Pourquoi la maîtresse écrit-elle à Madame Ouédraogo ?',
                'support' => "Bonjour Madame Ouédraogo,\nVotre fils Ibrahim n'est pas venu à l'école ce matin. Il est malade ? Merci de me téléphoner avant 16 h.\nMadame Kaboré, maîtresse de CE1\nÉcole du Centre, Ouagadougou",
                'choix' => ["Parce qu'Ibrahim est malade.", "Parce qu'Ibrahim n'est pas à l'école.", "Parce qu'Ibrahim est arrivé en retard ce matin.", "Parce que Madame Ouédraogo n'a pas téléphoné."],
                'bonne_reponse' => 1,
                'feedback' => 'Bravo, tu as vu que « Il est malade ? » est une question !',
                'explication' => "La maîtresse écrit : « Votre fils Ibrahim n'est pas venu à l'école ce matin. » Il est donc absent. Elle ne sait pas s'il est malade : « Il est malade ? » est une question. Il n'est pas en retard non plus, puisqu'il n'est pas venu du tout. Enfin, elle demande à sa mère de l'appeler (« Merci de me téléphoner avant 16 h ») : elle ne lui reproche pas de ne pas l'avoir fait.",
            ],
            [
                'niveau' => 'A2',
                'sous_niveau' => 'bas',
                'categorie' => 'Vie quotidienne',
                'enonce' => 'Awa travaille du lundi au vendredi, de 8 h à 17 h 30. Quand peut-elle aller au service Population ?',
                'support' => "Administration communale d'Ixelles – Service Population\nHoraires d'ouverture\nLundi, mercredi et vendredi : de 8 h 30 à 12 h 30\nMardi : de 8 h 30 à 12 h 30 et de 14 h à 16 h\nJeudi : de 13 h à 19 h, uniquement sur rendez-vous\nFermé le samedi et le dimanche",
                'choix' => ['Le lundi à 8 h 30', 'Le mardi à 16 h', 'Le jeudi à 18 h', 'Le samedi à 10 h'],
                'bonne_reponse' => 2,
                'feedback' => 'Excellent, tu as bien croisé les deux horaires !',
                'explication' => "Awa travaille jusqu'à 17 h 30 : elle ne peut venir qu'après. Le seul jour où le service est encore ouvert à cette heure-là, c'est le jeudi, « de 13 h à 19 h » (il faut prendre rendez-vous). Le lundi à 8 h 30 et le mardi à 16 h, Awa est au travail ; en plus, le mardi, le service ferme justement à 16 h. Le samedi, il est « Fermé ».",
            ],
            [
                'niveau' => 'A2',
                'sous_niveau' => 'bas',
                'categorie' => 'Annonces et affiches',
                'enonce' => 'Le 7 septembre, il pleut. Où a lieu le spectacle de musique ?',
                'support' => "Fête du quartier Saint-Roch\nSamedi 7 septembre\n10 h : course pour les enfants – parc Victoria\n12 h : dîner communautaire – parc Victoria (apportez un plat à partager)\n14 h : spectacle de musique – église Saint-Roch\n16 h : atelier de peinture pour tous – bibliothèque Gabrielle-Roy\nEn cas de pluie, toutes les activités ont lieu au centre communautaire.",
                'choix' => ['Au centre communautaire', "À l'église Saint-Roch", 'Au parc Victoria', 'À la bibliothèque Gabrielle-Roy'],
                'bonne_reponse' => 0,
                'feedback' => 'Bien vu, tu as pensé à lire la dernière ligne !',
                'explication' => "Normalement, le spectacle a lieu à l'« église Saint-Roch », mais l'affiche précise : « En cas de pluie, toutes les activités ont lieu au centre communautaire. » Le parc Victoria et la bibliothèque Gabrielle-Roy sont les lieux prévus pour les autres activités, par beau temps : la course, le dîner et l'atelier de peinture.",
            ],
            [
                'niveau' => 'A2',
                'sous_niveau' => 'moyen',
                'categorie' => 'Messages et courriels',
                'enonce' => 'Pourquoi Thomas écrit-il à Karim ?',
                'support' => "Objet : Samedi\nSalut Karim,\nMerci pour ton message ! Malheureusement, samedi, je ne peux pas t'aider pour ton déménagement : ma sœur se marie à Lyon ce week-end. Mais je suis libre le samedi suivant. Je peux venir t'aider à monter tes meubles ce jour-là. J'apporterai ma perceuse ! Je pourrai aussi prendre la voiture de mon père pour les cartons.\nÀ bientôt,\nThomas",
                'choix' => ['Pour inviter Karim au mariage de sa sœur, qui a lieu à Lyon ce week-end', "Pour demander à Karim de venir l'aider à monter ses meubles", "Pour dire qu'il n'est pas libre samedi et proposer un autre jour", 'Pour prêter à Karim la voiture de son père pour le déménagement'],
                'bonne_reponse' => 2,
                'feedback' => 'Bien joué, tu as compris le but du message !',
                'explication' => "Thomas répond à une demande de Karim : « samedi, je ne peux pas t'aider pour ton déménagement », puis il propose « le samedi suivant ». Il parle du mariage de sa sœur pour expliquer son absence, pas pour inviter Karim. C'est Thomas qui propose son aide, pas l'inverse : « Je peux venir t'aider à monter tes meubles. » Enfin, il ne prête pas la voiture de son père : il la prendra lui-même pour transporter les cartons.",
            ],
            [
                'niveau' => 'A2',
                'sous_niveau' => 'moyen',
                'categorie' => 'Vie quotidienne',
                'enonce' => 'Pourquoi Sofia a-t-elle écrit ce message ?',
                'support' => "Aux habitants du 12, rue de Carouge\nChers voisins,\nJe m'appelle Sofia et j'habite au 3e étage depuis lundi. Samedi soir, je fête mon anniversaire avec quelques amis. Il y aura de la musique, mais nous arrêterons à minuit. Excusez-moi d'avance pour le bruit ! Vous êtes tous invités à venir boire un verre avec nous à partir de 20 h.\nSofia (appartement 31)",
                'choix' => ['Pour se plaindre du bruit fait par ses voisins', 'Pour prévenir ses voisins et les inviter à sa fête', 'Pour présenter à ses voisins son nouvel appartement du 3e étage', "Pour annuler la fête d'anniversaire de samedi"],
                'bonne_reponse' => 1,
                'feedback' => "Bravo, tu as saisi l'intention de Sofia !",
                'explication' => "Sofia annonce sa fête (« Samedi soir, je fête mon anniversaire »), s'excuse pour le bruit et écrit « Vous êtes tous invités » : elle prévient ses voisins et les invite. Ce n'est pas elle qui se plaint du bruit, c'est elle qui va en faire. Elle dit seulement où elle habite (« au 3e étage »), sans présenter son appartement. Enfin, la fête n'est pas annulée : « nous arrêterons à minuit ».",
            ],
            [
                'niveau' => 'A2',
                'sous_niveau' => 'haut',
                'categorie' => 'Annonces et affiches',
                'enonce' => 'Selon le règlement, quelle phrase est vraie ?',
                'support' => "Résidence étudiante Les Bruyères – Louvain-la-Neuve\nRèglement\n- Les visites sont autorisées jusqu'à 23 h.\n- Il est interdit de faire des fêtes dans les kots. Pour une fête, vous pouvez réserver la salle commune.\n- Après chaque repas, nettoyez la cuisine.\n- Les vélos restent dans le garage, jamais dans les couloirs.\n- Les animaux ne sont pas acceptés, sauf les poissons.\n- Si vous perdez votre clé, la nouvelle clé coûte 25 euros.\nMerci de respecter ces règles.\nLe responsable de la résidence",
                'choix' => ["On peut recevoir des visites dans son kot jusqu'à minuit.", 'On peut laisser son vélo dans le couloir, juste devant sa porte.', "On peut avoir un chat dans son kot s'il reste calme.", 'On peut faire une fête dans la salle commune si on la réserve.'],
                'bonne_reponse' => 3,
                'feedback' => 'Très bien, tu as lu chaque règle avec attention !',
                'explication' => "Le règlement dit : « Il est interdit de faire des fêtes dans les kots. Pour une fête, vous pouvez réserver la salle commune. » La fête est donc possible dans la salle commune, avec une réservation. (En Belgique, un « kot » est une chambre d'étudiant.) Les visites sont autorisées « jusqu'à 23 h », pas jusqu'à minuit. Les vélos restent « dans le garage, jamais dans les couloirs ». Enfin, « Les animaux ne sont pas acceptés, sauf les poissons » : un chat est interdit, même calme.",
            ],
            [
                'niveau' => 'A2',
                'sous_niveau' => 'haut',
                'categorie' => 'Presse et médias',
                'enonce' => "Qu'a fait Paul Ngono pour être dans le journal ?",
                'support' => "Douala : une histoire qui finit bien\nMardi matin, Paul Ngono, chauffeur de taxi, a trouvé un sac sur le siège arrière de sa voiture. Dans le sac, il y avait des papiers et deux millions de francs CFA. Paul a tout de suite appelé la radio de la ville : « Je cherche la personne qui a oublié un sac dans mon taxi. » Deux heures plus tard, la propriétaire, une commerçante du marché central, est venue chercher son sac. Rien ne manquait. Pour remercier Paul, elle l'a invité au restaurant.",
                'choix' => ["Il a rendu tout l'argent trouvé dans son taxi.", 'Il a perdu un sac avec deux millions de francs CFA.', 'Il a parlé de son travail à la radio de la ville.', 'Il a ouvert un restaurant près du marché central.'],
                'bonne_reponse' => 0,
                'feedback' => "Bravo, tu as compris l'essentiel de l'article !",
                'explication' => "Paul a appelé la radio pour retrouver la propriétaire du sac, et quand elle est venue le chercher, « Rien ne manquait » : il a rendu tout l'argent. Ce n'est pas lui qui a perdu le sac, c'est la commerçante. À la radio, il n'a pas parlé de son travail : il a cherché « la personne qui a oublié un sac ». Enfin, le restaurant est le cadeau de la propriétaire (« elle l'a invité au restaurant »), et le marché central est son lieu de travail à elle.",
            ],
            [
                'niveau' => 'B1',
                'sous_niveau' => 'bas',
                'categorie' => 'Messages et courriels',
                'enonce' => "Comment Fatou se sent-elle aujourd'hui à Montréal ?",
                'support' => "Chère Amina,\nÇa fait déjà trois mois que je suis arrivée à Montréal ! Au début, c'était difficile : je ne connaissais personne et le froid m'a vraiment surprise. Je n'avais jamais vu autant de neige ! Heureusement, mes collègues m'ont beaucoup aidée. Samedi dernier, ils m'ont emmenée faire de la raquette sur le mont Royal, et j'ai adoré. Aujourd'hui, je me sens presque chez moi. Ma famille me manque beaucoup, mais je ne regrette pas mon choix. J'aimerais tellement te faire découvrir la ville cet été !\nGros bisous,\nFatou",
                'choix' => ['Seule, car elle ne connaît encore personne.', "Bien installée, malgré l'absence de sa famille.", "Découragée par le froid et la neige de l'hiver.", 'Pressée de rentrer voir sa famille cet été.'],
                'bonne_reponse' => 1,
                'feedback' => "Bien vu, tu as distingué le début du séjour et aujourd'hui !",
                'explication' => "Fatou écrit : « Aujourd'hui, je me sens presque chez moi » et « je ne regrette pas mon choix », même si « Ma famille me manque beaucoup ». C'est « Au début » qu'elle ne connaissait personne ; depuis, ses collègues l'ont aidée. Le froid l'a « surprise », sans la décourager : elle a « adoré » la raquette. Enfin, elle ne parle pas de rentrer cet été : elle voudrait faire découvrir Montréal à Amina.",
            ],
            [
                'niveau' => 'B1',
                'sous_niveau' => 'bas',
                'categorie' => 'Vie quotidienne',
                'enonce' => 'Que faut-il faire en partant, une fois la lessive terminée ?',
                'support' => "Buanderie – Mode d'emploi\n1. Réservez votre créneau sur le tableau, à l'entrée (deux heures au maximum).\n2. Versez la lessive dans le bac n° 2. Le bac n° 1 sert uniquement au prélavage.\n3. Choisissez le programme, puis appuyez sur « Départ ». Pendant le lavage, vous pouvez quitter la buanderie, mais revenez à l'heure : le locataire suivant attend peut-être.\n4. En partant, nettoyez le filtre du séchoir et laissez la porte de la machine ouverte, pour éviter les mauvaises odeurs.\nPas de lessive le dimanche ni après 22 h, par respect pour les voisins.\nLa gérance",
                'choix' => ['Réserver le créneau suivant sur le tableau.', 'Fermer la porte de la machine à laver en partant.', 'Nettoyer le filtre du séchoir à linge.', 'Vider le bac n° 1 réservé au prélavage.'],
                'bonne_reponse' => 2,
                'feedback' => "Très bien, tu as suivi les consignes jusqu'au bout !",
                'explication' => "L'étape 4 précise : « En partant, nettoyez le filtre du séchoir. » Le tableau sert à réserver son créneau avant la lessive (étape 1), pas en partant. La porte de la machine ne doit pas être fermée : il faut la laisser « ouverte, pour éviter les mauvaises odeurs ». Quant au bac n° 1, il « sert uniquement au prélavage » : le mode d'emploi ne demande pas de le vider.",
            ],
            [
                'niveau' => 'B1',
                'sous_niveau' => 'moyen',
                'categorie' => 'Presse et médias',
                'enonce' => "Quel est l'objectif principal de cette mesure ?",
                'support' => "Strasbourg teste les « rues scolaires »\nDepuis la rentrée, cinq rues situées devant des écoles sont fermées aux voitures deux fois par jour : de 8 h à 8 h 45 et de 16 h à 16 h 45. Selon la mairie, cette mesure doit rendre le trajet des enfants plus sûr et réduire la pollution de l'air devant les écoles. Les habitants de ces rues peuvent toujours sortir de chez eux en voiture, à condition de rouler très lentement. Les premiers résultats sont encourageants : les parents sont plus nombreux à venir à pied ou à vélo. Certains regrettent pourtant de devoir se garer plus loin. Si l'expérience est positive, la ville l'étendra à vingt autres écoles l'an prochain.",
                'choix' => ["Protéger les enfants et améliorer l'air près des écoles", 'Obliger les parents à se garer plus loin des écoles', 'Empêcher les habitants de sortir de chez eux en voiture', 'Étendre les rues scolaires à vingt autres écoles'],
                'bonne_reponse' => 0,
                'feedback' => "Bravo, tu as distingué l'objectif de ses conséquences !",
                'explication' => "Selon la mairie, la mesure « doit rendre le trajet des enfants plus sûr et réduire la pollution de l'air devant les écoles ». Se garer plus loin est une conséquence que certains parents « regrettent », pas un objectif. Les habitants « peuvent toujours sortir de chez eux en voiture », à condition de rouler très lentement. Enfin, l'extension à vingt autres écoles n'est qu'une possibilité : « Si l'expérience est positive ».",
            ],
            [
                'niveau' => 'B1',
                'sous_niveau' => 'moyen',
                'categorie' => 'Monde du travail',
                'enonce' => 'Pourquoi la direction organise-t-elle cette formation ?',
                'support' => "Note de service\nDe : Direction des ressources humaines\nÀ : Tout le personnel\nObjet : Formation à la sécurité incendie\nLors de l'exercice d'évacuation du 3 mars, plusieurs employés sont restés à leur poste malgré l'alarme. La direction a donc décidé d'organiser une formation à la sécurité incendie. Elle aura lieu le jeudi 20 mars, de 9 h à 11 h, dans la salle de conférence du 2e étage. La présence de tous est obligatoire, y compris pour les employés en télétravail ce jour-là. Il faut que chaque chef de service envoie la liste de son équipe avant le 14 mars. Un café sera servi dès 8 h 30.\nAbidjan, le 5 mars",
                'choix' => ["Parce qu'un incendie s'est déclaré au 2e étage le 3 mars", "Parce que le personnel en télétravail n'avait jamais été formé", "Parce que les chefs de service n'ont pas envoyé leur liste", "Parce que des employés ont ignoré l'alarme le 3 mars"],
                'bonne_reponse' => 3,
                'feedback' => "Excellent, le mot « donc » t'a mis sur la bonne piste !",
                'explication' => "La note explique : « Lors de l'exercice d'évacuation du 3 mars, plusieurs employés sont restés à leur poste malgré l'alarme. La direction a donc décidé… » Le mot « donc » introduit la conséquence. Le 3 mars, il s'agissait d'un exercice, pas d'un vrai incendie. La note ne dit rien de la formation passée des employés en télétravail : elle leur demande seulement d'être présents. Enfin, les chefs de service doivent envoyer leur liste « avant le 14 mars » : c'est une consigne pour la suite, pas la cause de la formation.",
            ],
            [
                'niveau' => 'B1',
                'sous_niveau' => 'haut',
                'categorie' => 'Textes argumentatifs',
                'enonce' => "Quelle est l'opinion de Nathalie ?",
                'support' => "Courrier des lecteurs – Le cellulaire interdit à l'école : bonne idée ?\n« Enseignante au secondaire, je vois chaque jour des élèves incapables de se concentrer plus de dix minutes. Mon collègue Martin pense que l'interdiction ne sert à rien, puisque les jeunes utiliseront de toute façon leur téléphone à la maison. C'est vrai, mais justement : l'école doit être un lieu où l'on apprend à s'en passer. Certains parents s'inquiètent de ne plus pouvoir joindre leurs enfants ; pourtant, le secrétariat a toujours un téléphone en cas d'urgence. Depuis que notre école a adopté cette règle, en septembre, je constate déjà une différence : les récréations sont plus animées et les cours plus calmes. Pour moi, il ne s'agit pas de punir les élèves, mais de leur redonner du temps pour se concentrer et pour se parler. C'est pourquoi j'appuie cette mesure sans hésiter. »\nNathalie, Sherbrooke",
                'choix' => ["L'interdiction est inutile, car les élèves ont un téléphone à la maison.", "L'interdiction aide les élèves à retrouver leur concentration.", 'Il faut punir les élèves qui utilisent leur téléphone en classe.', 'Les parents doivent pouvoir joindre leurs enfants à tout moment.'],
                'bonne_reponse' => 1,
                'feedback' => "Bravo, tu as bien séparé l'avis de Nathalie de celui des autres !",
                'explication' => "Nathalie conclut : « C'est pourquoi j'appuie cette mesure sans hésiter », car elle veut « redonner du temps pour se concentrer » aux élèves. L'idée que l'interdiction « ne sert à rien » est celle de son collègue Martin, qu'elle conteste (« C'est vrai, mais justement »). Elle précise aussi qu'« il ne s'agit pas de punir les élèves ». Enfin, elle cite l'inquiétude des parents pour y répondre : « pourtant, le secrétariat a toujours un téléphone en cas d'urgence ».",
            ],
            [
                'niveau' => 'B1',
                'sous_niveau' => 'haut',
                'categorie' => 'Textes littéraires',
                'enonce' => "Que pense aujourd'hui la narratrice de son choix de métier ?",
                'support' => "Quand j'ai annoncé à ma famille que je voulais devenir couturière, personne n'a applaudi. Mon père voulait que je devienne médecin, comme mon oncle de Cotonou. Ma mère, elle, trouvait que c'était un beau métier, mais trop fatigant pour les yeux. Seule ma grand-mère n'a rien dit : elle m'a simplement donné sa vieille machine à coudre, celle qu'elle avait apportée de Porto-Novo quand elle s'était mariée.\nAujourd'hui, j'ai mon propre atelier et trois apprenties. Des clientes viennent parfois de loin pour mes robes en pagne, et mon père porte fièrement les chemises que je lui couds. Je crois que ma grand-mère avait compris avant tout le monde : on ne choisit pas un métier pour faire plaisir, on le choisit parce qu'il nous fait vivre, dans tous les sens du mot.",
                'choix' => ['Son père avait raison : médecin était un meilleur choix.', 'Couturière est un beau métier, mais trop fatigant pour les yeux.', "Elle a eu raison de faire le métier qu'elle aimait.", 'On doit choisir un métier qui fait plaisir à sa famille.'],
                'bonne_reponse' => 2,
                'feedback' => 'Bien joué, tu as reconnu la voix de la narratrice parmi les autres !',
                'explication' => "La narratrice a aujourd'hui son « propre atelier », son père porte « fièrement » ses chemises, et elle conclut : « on ne choisit pas un métier pour faire plaisir ». Elle ne regrette donc pas son choix. Devenir médecin était le souhait de son père (« Mon père voulait que je devienne médecin »), et « un beau métier, mais trop fatigant pour les yeux » est l'avis de sa mère. Enfin, choisir un métier pour faire plaisir à sa famille, c'est justement ce qu'elle refuse.",
            ],
            [
                'niveau' => 'B2',
                'sous_niveau' => 'bas',
                'categorie' => 'Messages et courriels',
                'enonce' => "Que propose l'entreprise à la cliente ?",
                'support' => "Madame,\nNous avons bien reçu votre courriel du 12 mai concernant le retard de livraison de votre canapé, et nous vous prions de nous en excuser. Bien que notre transporteur ait rencontré d'importantes difficultés ce mois-ci, vous auriez dû être informée de ce retard sans avoir à nous contacter. Votre canapé vous sera livré le 28 mai, entre 8 h et 13 h. À titre de dédommagement, les frais de livraison, soit 49 euros, vous seront intégralement remboursés sous dix jours.\nEn revanche, nous ne pouvons pas donner suite à votre demande d'annulation sans frais : votre commande ayant déjà quitté notre entrepôt, elle ne peut plus être modifiée. Si vous refusez la livraison, des frais de retour vous seront facturés, conformément à nos conditions générales de vente.\nNous vous remercions de votre patience et restons à votre disposition pour toute question.\nLe service client",
                'choix' => ['De lui rembourser les frais de livraison', "D'annuler sa commande sans aucun frais", 'De lui accorder 49 euros de réduction sur un prochain achat', 'De la faire livrer plus vite par un autre transporteur'],
                'bonne_reponse' => 0,
                'feedback' => 'Excellent, tu as repéré la réserve introduite par « En revanche » !',
                'explication' => "L'entreprise écrit : « À titre de dédommagement, les frais de livraison, soit 49 euros, vous seront intégralement remboursés. » C'est un remboursement, pas une réduction sur un prochain achat. L'annulation sans frais est refusée : « En revanche, nous ne pouvons pas donner suite à votre demande d'annulation sans frais ». Enfin, la lettre ne parle pas de changer de transporteur : elle fixe une nouvelle date de livraison, le 28 mai.",
            ],
            [
                'niveau' => 'B2',
                'sous_niveau' => 'bas',
                'categorie' => 'Presse et médias',
                'enonce' => "Laquelle de ces phrases exprime une opinion de l'auteur, et non un fait ?",
                'support' => "Dakar : des salles de classe en briques de plastique\nDepuis trois ans, une petite entreprise de Dakar transforme les déchets plastiques en briques légères et solides, avec lesquelles on construit des salles de classe. Chaque classe nécessite environ quatre tonnes de plastique, ramassé dans les quartiers par des collecteuses payées au kilo. Une quinzaine d'écoles en ont déjà bénéficié dans la région de Thiès. Les briques coûtent un peu plus cher que le béton, mais elles isolent mieux de la chaleur, ce que les enseignants apprécient.\nOn ne peut que saluer une idée qui répond à deux urgences à la fois : la pollution et le manque de salles de classe. Mais attention à ne pas se tromper de diagnostic. Le pays produit chaque année d'énormes quantités de déchets plastiques, dont seule une petite partie est recyclée. Tant que les emballages jetables resteront la norme, ces briques ne feront que déplacer le problème.",
                'choix' => ['Chaque classe nécessite environ quatre tonnes de plastique.', 'Les collecteuses de plastique sont payées au kilo.', "Une quinzaine d'écoles ont déjà profité de ces classes.", 'Ces briques ne suffiront pas à régler le problème.'],
                'bonne_reponse' => 3,
                'feedback' => "Bravo, tu sais distinguer un fait d'une opinion !",
                'explication' => "La phrase « Tant que les emballages jetables resteront la norme, ces briques ne feront que déplacer le problème » exprime un jugement de l'auteur : c'est sa prévision, qu'on peut discuter. Les trois autres réponses reprennent des faits vérifiables, présentés sans commentaire : « Chaque classe nécessite environ quatre tonnes de plastique », les collecteuses sont « payées au kilo » et « Une quinzaine d'écoles en ont déjà bénéficié ».",
            ],
            [
                'niveau' => 'B2',
                'sous_niveau' => 'moyen',
                'categorie' => 'Textes argumentatifs',
                'enonce' => "Quelle est la position de l'éditorialiste ?",
                'support' => "Éditorial – Le calendrier scolaire, trois ans après\nIl faut le reconnaître : la réforme du calendrier scolaire partait d'une bonne intention. Des vacances d'été un peu plus courtes, deux vraies semaines de repos à la Toussaint et au carnaval : les chronobiologistes le réclamaient depuis longtemps, et les enseignants constatent que les élèves reviennent moins fatigués.\nOr une réforme ne se juge pas seulement sur ses principes. Faute d'accord avec la Flandre, qui a conservé l'ancien calendrier, des milliers de familles vivent désormais à contretemps. Prenons les Janssens, à Bruxelles : leur fille est dans une école francophone, leur fils dans une école néerlandophone. Résultat : plusieurs semaines de congé en décalé chaque année, autant de gardes à organiser. Leur cas n'a rien d'exceptionnel dans la capitale, où de nombreux parents ont choisi le néerlandais pour l'un de leurs enfants.\nCertes, personne ne propose de revenir en arrière. Mais tant que les communautés refuseront de se parler, c'est aux parents qu'on laissera le soin de faire le lien.",
                'choix' => ['La réforme doit être abandonnée, car elle épuise les élèves et les enseignants.', "La Flandre a eu raison de garder l'ancien calendrier scolaire.", 'Le principe est bon, mais le manque de coordination pénalise les familles.', 'Les parents devraient inscrire tous leurs enfants dans une école de la même langue.'],
                'bonne_reponse' => 2,
                'feedback' => "Très bien, tu as suivi le raisonnement jusqu'au « Or » !",
                'explication' => "L'éditorialiste reconnaît d'abord que la réforme « partait d'une bonne intention » (les élèves « reviennent moins fatigués »), puis il introduit sa critique par « Or » : « Faute d'accord avec la Flandre […], des milliers de familles vivent désormais à contretemps. » Il ne demande pas l'abandon de la réforme : « personne ne propose de revenir en arrière ». Il ne donne pas raison à la Flandre : il reproche aux communautés de refuser « de se parler ». Enfin, l'exemple des Janssens illustre le problème : l'auteur ne conseille pas aux parents de changer leurs enfants d'école.",
            ],
            [
                'niveau' => 'B2',
                'sous_niveau' => 'moyen',
                'categorie' => 'Monde du travail',
                'enonce' => 'Pourquoi le chroniqueur parle-t-il de Yanis ?',
                'support' => "Chronique – La commande qui coûte cher\nIl est 21 h, il pleut, et votre repas arrive en vingt minutes. Magique ? Pas pour tout le monde. Prenons Yanis, livreur à vélo à Bordeaux depuis deux ans. Pour une course de quatre kilomètres, l'application lui verse 3,80 euros. Les soirs de pluie, les commandes se multiplient, mais pas le tarif. Yanis n'a ni congés payés ni assurance en cas d'accident, et s'il refuse trop de commandes, son compte peut être suspendu sans explication. Lorsqu'il chute sur la chaussée mouillée, c'est à lui de payer la réparation de son vélo, et chaque jour d'arrêt est un jour sans revenu.\nCertes, ce travail offre une souplesse que beaucoup apprécient, notamment les étudiants. Et il serait malhonnête de nier que, pendant les confinements, les livreurs ont permis à de nombreux restaurants de survivre. Mais cette souplesse a un prix, et ce ne sont pas les clients qui le paient. La prochaine fois que vous commanderez, regardez donc qui sonne à votre porte : ce n'est pas un service, c'est quelqu'un.",
                'choix' => ['Pour prouver que les livreurs ont sauvé les restaurants', 'Pour montrer concrètement la précarité des livreurs', 'Pour conseiller aux étudiants de devenir livreurs', 'Pour dénoncer les clients qui commandent quand il pleut'],
                'bonne_reponse' => 1,
                'feedback' => "Bien joué, tu as compris à quoi sert l'exemple de Yanis !",
                'explication' => "Le chroniqueur présente Yanis juste après « Pas pour tout le monde » et décrit sa situation : 3,80 euros la course, « ni congés payés ni assurance », un compte qui « peut être suspendu sans explication ». C'est un exemple concret de la précarité des livreurs. Leur rôle pendant les confinements est une concession (« il serait malhonnête de nier… »), pas le but de l'exemple. La souplesse appréciée par « les étudiants » est reconnue, pas conseillée. Enfin, l'auteur ne dénonce pas les clients : il leur demande seulement de regarder « qui sonne à votre porte ».",
            ],
            [
                'niveau' => 'B2',
                'sous_niveau' => 'haut',
                'categorie' => 'Textes littéraires',
                'enonce' => 'Que ressent Mame Coumba quand elle voit enfin son petit-fils ?',
                'support' => "Mame Coumba était arrivée à l'aéroport bien avant l'aube, alors que l'avion de Montréal, qui ramenait son petit-fils, ne devait atterrir qu'à dix heures. Elle avait mis son boubou bleu, celui des grandes occasions, enveloppé dans un torchon les beignets préparés la veille, et refusé le café que lui proposait son neveu. Elle ne s'assit pas une seule fois. « Assieds-toi, Mame, il est encore tôt », répétait son neveu ; elle faisait semblant de ne pas entendre. Toutes les cinq minutes, elle allait vérifier l'écran des arrivées, qu'elle ne savait pourtant pas lire. Quand son neveu lui annonça enfin que l'avion avait atterri, elle lui serra si fort la main qu'il faillit crier.\nLes portes vitrées s'ouvrirent et se refermèrent cent fois sur des inconnus. Elle scrutait chaque visage, et chaque visage la décevait. Puis elle le vit : plus grand, plus mince, avec cette barbe qu'elle ne lui connaissait pas. Elle ne courut pas. Elle resta là, immobile, les mains sur la bouche, pendant que les larmes coulaient sans bruit sur ses joues. Ce fut lui qui traversa le hall en courant.\nSix ans. Il avait fallu six ans.",
                'choix' => ["Une émotion si forte qu'elle en reste figée", 'Une impatience qui la fait courir vers lui', 'Une déception, car il a beaucoup changé', "Une colère contenue après six ans d'absence"],
                'bonne_reponse' => 0,
                'feedback' => "Très belle lecture, tu as su lire l'émotion entre les lignes !",
                'explication' => "Le texte ne nomme pas le sentiment, il le montre : « Elle ne courut pas. Elle resta là, immobile, les mains sur la bouche, pendant que les larmes coulaient sans bruit sur ses joues. » L'émotion la submerge au point qu'elle ne peut plus bouger. Ce n'est donc pas elle qui court : « Ce fut lui qui traversa le hall en courant. » Le verbe « décevait » concerne les inconnus qui sortaient avant lui, pas son petit-fils. Enfin, rien n'indique de la colère : « Six ans » souligne la longueur de l'attente, pas un reproche.",
            ],
            [
                'niveau' => 'B2',
                'sous_niveau' => 'haut',
                'categorie' => 'Presse et médias',
                'enonce' => "Pourquoi l'auteur écrit-il que les photos de glaciers ne sont que « la partie visible de l'iceberg » ?",
                'support' => "Glaciers : la partie visible de l'iceberg\nChaque été, les images reviennent : des glaciers suisses qui reculent de plusieurs dizaines de mètres, des bâches blanches déployées pour protéger la glace du soleil, des alpinistes qui découvrent des rochers jamais vus. Ces photos spectaculaires ont le mérite d'alerter l'opinion. Mais elles ne sont que la partie visible de l'iceberg.\nCar un glacier n'est pas seulement un décor de carte postale : c'est un réservoir. On parle d'ailleurs des Alpes comme du « château d'eau » de l'Europe. L'hiver, il stocke l'eau sous forme de neige et de glace ; l'été, quand les pluies se font rares, il la libère peu à peu. Le Rhône, par exemple, est largement alimenté par la fonte des glaciers pendant les mois chauds. Leur disparition menace donc bien plus que le tourisme : l'irrigation des vignes valaisannes, la production des barrages hydroélectriques et même le refroidissement de certaines centrales situées en aval pourraient être touchés lors des étés secs. Lorsque ce réservoir se vide, c'est tout un équilibre qui vacille.\nAutrement dit, le vrai danger ne se voit pas sur les photos. Il se mesurera en litres, pas en mètres.",
                'choix' => ['Parce que les glaciers suisses finiront par devenir des icebergs', 'Parce que la fonte des glaciers est surtout un problème pour le tourisme', 'Parce que les photographes exagèrent souvent le recul des glaciers', "Parce que les pires conséquences, sur l'eau, ne se voient pas"],
                'bonne_reponse' => 3,
                'feedback' => "Bravo, tu as compris l'expression imagée dans son contexte !",
                'explication' => "« La partie visible de l'iceberg », c'est la petite partie visible d'un problème bien plus vaste. L'auteur l'explique ensuite : un glacier est « un réservoir », et sa disparition menace l'irrigation, les barrages et les centrales ; « le vrai danger ne se voit pas sur les photos ». L'expression est imagée : les glaciers ne vont pas devenir des icebergs. Le tourisme n'est pas l'essentiel, puisque la disparition des glaciers « menace donc bien plus que le tourisme ». Enfin, l'auteur ne critique pas les photos : elles « ont le mérite d'alerter l'opinion ».",
            ],
            [
                'niveau' => 'C1',
                'sous_niveau' => 'bas',
                'categorie' => 'Presse et médias',
                'enonce' => "D'après l'article, que peut-on affirmer ?",
                'support' => "Sommeil : les écrans du soir en accusation ?\nLes adolescents qui utilisent leur téléphone dans l'heure qui précède le coucher dormiraient en moyenne quarante minutes de moins que les autres. C'est du moins ce qui ressort d'une vaste enquête, dont les résultats viennent d'être publiés, menée auprès de 4 000 élèves du secondaire par une équipe de chercheurs québécois. Les participants, âgés de 12 à 17 ans, ont décrit pendant deux semaines leurs habitudes du soir et leurs heures de coucher. Le phénomène serait plus marqué le week-end, lorsque les horaires se relâchent.\nFaut-il pour autant conclure que les écrans sont la cause de ces nuits écourtées ? Les auteurs s'en gardent bien. Leur étude, fondée sur des questionnaires, établit une association, non un lien de causalité : il n'est pas exclu que ce soient les jeunes qui dorment mal qui se tournent vers leur téléphone, plutôt que l'inverse. D'autres facteurs, comme le stress scolaire ou les horaires des activités sportives, pourraient également jouer un rôle.\nLes chercheurs recommandent néanmoins, par précaution, de laisser les appareils hors de la chambre. Une seconde phase de l'étude, qui devrait débuter l'automne prochain, mesurera le sommeil à l'aide de bracelets connectés, afin de mieux distinguer les causes des effets. Ses résultats ne sont pas attendus avant deux ans.",
                'choix' => ["L'étude a démontré que les écrans font perdre quarante minutes de sommeil.", "L'étude observe un lien entre écrans et sommeil, sans en établir la cause.", 'Le stress scolaire est la véritable cause des nuits trop courtes.', "La seconde phase de l'étude a confirmé les premiers résultats."],
                'bonne_reponse' => 1,
                'feedback' => 'Excellent, tu as bien mesuré la prudence des chercheurs !',
                'explication' => "Les chercheurs établissent « une association, non un lien de causalité » : ils observent un lien entre écrans et sommeil, sans savoir lequel entraîne l'autre. Le conditionnel « dormiraient » et la question « Faut-il pour autant conclure… ? » montrent que rien n'a été démontré. Le stress scolaire fait partie des facteurs qui « pourraient également jouer un rôle » : c'est une hypothèse, pas une cause établie. Enfin, la seconde phase « devrait débuter l'automne prochain » : elle n'a encore rien confirmé.",
            ],
            [
                'niveau' => 'C1',
                'sous_niveau' => 'bas',
                'categorie' => 'Monde du travail',
                'enonce' => "Que révèle l'enquête interne sur le plan humain ?",
                'support' => "Note de synthèse – Bilan de l'expérience de télétravail\nÀ l'issue de douze mois d'expérimentation, le comité de pilotage dresse un bilan contrasté. Dans les services administratifs, la productivité mesurée a progressé de 6 %, une hausse que les responsables attribuent principalement à la diminution des interruptions, même si une partie de cette progression pourrait tenir à l'arrivée simultanée d'un nouvel outil de gestion des dossiers. Dans les équipes techniques, elle est restée stable, ce qui n'a rien de surprenant, la plupart des interventions exigeant une présence sur site. Quant au service clientèle, les données recueillies, incomplètes en raison d'un changement de logiciel en cours d'année, ne permettent de tirer aucune conclusion fiable.\nSur le plan humain, l'enquête interne fait apparaître une nette amélioration de la satisfaction, à nuancer toutefois : près d'un salarié sur cinq déclare se sentir isolé, proportion qui atteint un sur trois chez les nouveaux arrivants.\nLe comité recommande par conséquent de pérenniser le dispositif, à raison de deux jours de télétravail par semaine au maximum, et d'imposer aux nouveaux arrivants une présence à temps plein durant leurs trois premiers mois. Une nouvelle évaluation du service clientèle sera menée au terme de l'exercice 2027.\nDirection des ressources humaines – Namur, le 30 juin 2026",
                'choix' => ['Un salarié sur trois se sent isolé depuis la mise en place du télétravail.', 'La satisfaction des salariés a nettement baissé chez les nouveaux arrivants.', "La satisfaction s'améliore, mais l'isolement frappe davantage les nouveaux.", "L'isolement a disparu depuis la limite de deux jours de télétravail."],
                'bonne_reponse' => 2,
                'feedback' => "Bien vu, tu as vérifié à qui s'applique chaque chiffre !",
                'explication' => "La note fait état d'« une nette amélioration de la satisfaction, à nuancer toutefois » : « près d'un salarié sur cinq » se sent isolé, « proportion qui atteint un sur trois chez les nouveaux arrivants ». Le chiffre d'un sur trois ne vaut donc que pour les nouveaux, pas pour l'ensemble des salariés. Rien n'indique une baisse de la satisfaction chez eux : le texte parle d'isolement. Enfin, la limite de deux jours par semaine est une recommandation pour l'avenir, pas un résultat de l'enquête.",
            ],
            [
                'niveau' => 'C1',
                'sous_niveau' => 'moyen',
                'categorie' => 'Textes argumentatifs',
                'enonce' => "Quelle attitude l'auteure adopte-t-elle envers les décideurs ?",
                'support' => "Tribune – Apprendre à lire en bambara : cessons de tergiverser\nVoilà plus de trente ans que l'on expérimente, dans quelques dizaines d'écoles, l'enseignement en langues nationales durant les premières années du primaire. Voilà plus de trente ans que les évaluations se suivent et se ressemblent : les enfants qui apprennent d'abord à lire dans la langue qu'ils parlent à la maison lisent mieux, y compris en français, que ceux à qui l'on impose d'emblée une langue qu'ils ne comprennent pas. Les rapports s'empilent ; les classes, elles, attendent.\nNul ne conteste plus ces résultats. On invoque en revanche, avec une remarquable constance, le manque de manuels, la formation insuffisante des maîtres, la multiplicité des langues, et jusqu'à la crainte, rarement formulée à voix haute, que l'école ne perde en prestige ce qu'elle gagnerait en efficacité. Autant d'obstacles bien réels, que trois décennies auraient pourtant amplement suffi à lever, pour peu qu'on s'en soit donné la peine.\nIl ne s'agit nullement de tourner le dos au français, qui demeure une langue d'ouverture sur le monde et que nos enfants doivent maîtriser. Il s'agit de leur permettre d'y accéder par la seule porte qu'ils connaissent déjà. À force de prudence, on finit par confondre la patience avec l'immobilisme. Nos décideurs ont aujourd'hui toutes les cartes en main ; il ne leur reste plus qu'à les jouer.\nKadiatou Sangaré, enseignante à Ségou (Mali)",
                'choix' => ["Elle salue leur prudence face à des obstacles qu'elle juge bien réels.", "Elle les accuse d'avoir voulu supprimer le français.", "Elle conteste les évaluations sur lesquelles ils s'appuient.", 'Elle leur reproche, sans le dire franchement, de ne pas agir.'],
                'bonne_reponse' => 3,
                'feedback' => 'Très bien, tu as perçu le reproche derrière la retenue !',
                'explication' => "L'auteure n'attaque jamais les décideurs de front, mais tout son texte leur reproche leur inaction : les obstacles auraient pu être levés en trente ans « pour peu qu'on s'en soit donné la peine », et « À force de prudence, on finit par confondre la patience avec l'immobilisme ». Elle reconnaît des obstacles « bien réels », mais elle ne salue pas cette prudence : elle la dénonce. Elle n'accuse personne de vouloir supprimer le français ; elle précise au contraire qu'« il ne s'agit nullement de tourner le dos au français ». Enfin, elle ne conteste pas les évaluations : « Nul ne conteste plus ces résultats ».",
            ],
            [
                'niveau' => 'C1',
                'sous_niveau' => 'moyen',
                'categorie' => 'Presse et médias',
                'enonce' => 'Quel est, au fond, le jugement de la critique sur ce film ?',
                'support' => "Cinéma – Les Hivers de Rosalie\nIl y a tout, dans le troisième long métrage de Julie Morin : une maison de ferme en Gaspésie, trois sœurs brouillées depuis la mort de leur père, des secrets qui remontent à la surface au rythme de la fonte des neiges. Il y a surtout Émilie Gagnon, bouleversante dans le rôle de l'aînée, qui parvient à tout dire d'un regard. Ses deux partenaires, plus en retrait, ne déméritent pas. Présenté en ouverture du Festival de cinéma de la ville de Québec, le film était très attendu.\nLa photographie est d'une beauté à couper le souffle ; chaque plan pourrait être accroché dans un musée. C'est peut-être là que le bât blesse. À force de soigner ses cadres, la réalisatrice semble avoir oublié de faire respirer ses personnages, qui passent plus de temps à contempler le fleuve qu'à se parler. Filmé à toutes les heures du jour, le fleuve finit d'ailleurs par voler la vedette aux comédiens. Les dialogues, rares, sonnent souvent comme des sentences, et l'on devine chaque révélation une bonne demi-heure avant qu'elle ne survienne. La musique, elle, accompagne le tout avec une discrétion bienvenue.\nOn ne s'ennuie pas vraiment : on admire. Mais l'émotion reste de l'autre côté de l'écran, sagement encadrée. Un film magnifique, donc, au sens premier du terme : fait pour être regardé bien plus que pour être vécu.",
                'choix' => ['Un film beau à regarder, mais qui ne touche pas vraiment.', 'Un film ennuyeux, sauvé seulement par son actrice principale.', 'Un film bouleversant, dont les dialogues sont la grande force.', 'Un film trop réaliste, qui ressemble à un documentaire sur la Gaspésie.'],
                'bonne_reponse' => 0,
                'feedback' => 'Bien vu, tu as lu la réserve derrière les compliments !',
                'explication' => "La critique loue la beauté des images (« d'une beauté à couper le souffle ») mais regrette le manque d'émotion : « l'émotion reste de l'autre côté de l'écran ». Sa conclusion le résume : le film est « fait pour être regardé bien plus que pour être vécu ». Elle ne le trouve pas ennuyeux : « On ne s'ennuie pas vraiment : on admire. » Le mot « bouleversante » qualifie l'actrice, pas le film, et les dialogues sont critiqués : ils « sonnent souvent comme des sentences ». Enfin, rien n'indique que le film ressemble à un documentaire : la Gaspésie n'est que le décor de l'histoire.",
            ],
            [
                'niveau' => 'C1',
                'sous_niveau' => 'haut',
                'categorie' => 'Textes littéraires',
                'enonce' => 'Que suggère la fin du texte ?',
                'support' => "Le pot de départ avait lieu dans la salle de réunion du troisième étage, celle dont la fenêtre ne fermait plus depuis des années. Monsieur Vasseur, le directeur, fit un discours. Il parla de fidélité, de « pilier de la maison », de trente-deux années de bons et loyaux services. Il se trompa sur le prénom de la femme de Bernard, puis sur le nombre de ses petits-enfants, mais qui aurait pu lui en vouloir ? Il était si occupé. On but du mousseux tiède dans des gobelets en plastique, sous une banderole « Bonne retraite ! » accrochée légèrement de travers.\nOn offrit à Bernard une montre. Une belle montre, vraiment, avec un bracelet en acier et un cadran bleu nuit. Bernard la tourna longuement entre ses doigts. Trente-deux ans, et on lui offrait de quoi mesurer le temps. Il y avait sans doute là une ironie que personne n'avait vue, ou que tout le monde avait vue sans oser le dire.\nIl remercia. Il dit que la maison allait lui manquer, ce qui était vrai, et qu'il partait sans regret, ce qui l'était moins. Puis il serra des mains, beaucoup de mains, dont certaines appartenaient à des gens dont il ignorait tout. Une stagiaire lui souhaita « bon courage pour la suite », comme on le dit à ceux qui changent de service. Quand il rentra chez lui, sa femme lui demanda comment cela s'était passé.\n— Très bien, dit-il. Ils ont été très gentils.\nEt il rangea la montre, dans son écrin, au fond du tiroir de la commode.",
                'choix' => ['Bernard range la montre avec soin, car il y tient beaucoup.', "Bernard compte offrir la montre à l'un de ses petits-enfants.", "Bernard est plus blessé par ce départ qu'il ne veut l'avouer.", 'Bernard trouve que ses collègues ont été sincèrement gentils.'],
                'bonne_reponse' => 2,
                'feedback' => 'Superbe, tu as entendu ce que Bernard ne dit pas !',
                'explication' => "Plusieurs indices révèlent une déception que Bernard cache : il dit partir sans regret, « ce qui l'était moins » (c'est-à-dire moins vrai), puis il répond à sa femme « Ils ont été très gentils » avant de ranger la montre « au fond du tiroir de la commode », là où on ne la verra plus. Ranger un objet au fond d'un tiroir, ce n'est pas le garder précieusement. Rien n'indique qu'il veuille la donner à ses petits-enfants, dont le directeur ne connaissait même pas le nombre. Enfin, « Ils ont été très gentils » est une formule de politesse : le texte montre un directeur qui se trompe sur sa famille et des gens dont Bernard « ignorait tout ».",
            ],
            [
                'niveau' => 'C1',
                'sous_niveau' => 'haut',
                'categorie' => 'Textes littéraires',
                'enonce' => 'Que suggère la comparaison finale avec une tombe ?',
                'support' => "Le car postal me déposa sur la place, à l'endroit exact où, petite, j'attendais celui de l'école. Je n'étais pas revenue depuis trente ans. La fontaine était toujours là, et le tilleul, et même le banc d'où le vieux Crettex commentait le passage des voitures comme d'autres commentent les combats de lutte. L'odeur du foin coupé m'attendait au coin de la rue, comme autrefois.\nMais le village avait changé de visage sans changer de traits. Les chalets n'avaient pas bougé ; ils avaient seulement cessé de vivre. Les géraniums avaient disparu des balcons, remplacés par de petites caméras blanches. Leurs volets, rouges ou verts selon les familles, restaient clos d'un bout à l'autre de la semaine, comme des yeux qui n'attendent plus personne. On les ouvrait, m'expliqua la boulangère, « à Noël, à Pâques, et quand il neige bien ». Le reste du temps, les propriétaires vivaient à Genève, à Zurich ou à Londres, et le village leur servait de fond d'écran. Le café du Commerce était devenu une agence immobilière.\nJe remontai la rue jusqu'à la maison de ma grand-mère. On l'avait repeinte, agrandie, dotée d'une terrasse vitrée où trônait un jacuzzi. Le potager où ma grand-mère m'apprenait à reconnaître les salades avait laissé place à un gazon impeccable. Sur la boîte aux lettres, un nom que je ne savais pas prononcer. Je restai longtemps devant la barrière, comme on reste devant une tombe dont on n'est plus tout à fait sûr qu'elle soit la bonne.",
                'choix' => ['La grand-mère de la narratrice a été enterrée près de sa maison.', "La narratrice pleure une maison qu'elle ne reconnaît presque plus.", "La maison de la grand-mère est aujourd'hui abandonnée et en ruine.", "La narratrice regrette d'avoir vendu la maison à des étrangers."],
                'bonne_reponse' => 1,
                'feedback' => "Très fine lecture, tu as saisi toute la force de l'image !",
                'explication' => "On se recueille devant une tombe quand on a perdu quelqu'un : la narratrice vit la transformation de la maison comme un deuil. La fin de la phrase, « dont on n'est plus tout à fait sûr qu'elle soit la bonne », montre qu'elle a du mal à la reconnaître : la maison a été repeinte, agrandie, et porte sur la boîte aux lettres « un nom que je ne savais pas prononcer ». La comparaison est une image : le texte ne dit pas que la grand-mère est enterrée là. La maison n'est pas en ruine, puisqu'on l'a « repeinte, agrandie ». Enfin, rien n'indique que la narratrice l'ait vendue elle-même.",
            ],
            [
                'niveau' => 'C2',
                'sous_niveau' => 'bas',
                'categorie' => 'Textes argumentatifs',
                'enonce' => "Laquelle de ces affirmations découle du raisonnement de l'auteur ?",
                'support' => "On a longtemps tenu l'oubli pour une défaillance : une mémoire qui flanche, une archive qui brûle, un nom qui se dérobe. L'ère numérique semblait devoir nous en délivrer. Tout se conserve désormais, et tout se retrouve, pour peu qu'on sache chercher. Nos téléphones se souviennent à notre place de ce que nous avons mangé il y a trois ans, des rues où nous sommes passés, des mots que nous avons écrits dans la colère. Or cette victoire apparente sur l'oubli pourrait bien se révéler une défaite pour la mémoire elle-même.\nCar se souvenir n'est pas stocker. La mémoire humaine ne restitue jamais le passé tel quel : elle le trie, le hiérarchise, le recompose à la lumière de ce que nous sommes devenus. C'est précisément parce qu'elle oublie qu'elle peut donner sens : l'oubli n'est pas l'ennemi de la mémoire, il en est l'atelier. Un souvenir qui ne s'effacerait jamais, qui ne se transformerait jamais, ne serait plus un souvenir, mais un document ; il ne nous appartiendrait plus, il nous lierait.\nIl ne s'ensuit pas qu'il faille détruire les archives, ni que toute conservation soit suspecte. Les sociétés ont besoin de traces, ne serait-ce que pour rendre justice. Mais une trace n'est un souvenir qu'à condition d'être reprise, interprétée, parfois contestée par une conscience. L'accumulation, à elle seule, n'y suffit pas : elle en est même, lorsqu'elle devient totale, l'exact contraire. Ce que le numérique menace, ce n'est donc pas notre capacité à retenir, mais notre liberté de devenir autre chose que la somme de ce que nous avons été.",
                'choix' => ['Conserver une trace ne suffit pas à en faire un souvenir.', "Toute conservation d'archives numériques menace la mémoire.", "Il suffit d'interpréter une trace pour qu'elle devienne un souvenir.", 'Le numérique affaiblit notre capacité à retenir les informations.'],
                'bonne_reponse' => 0,
                'feedback' => 'Remarquable, tu as distingué condition nécessaire et condition suffisante !',
                'explication' => "L'auteur affirme qu'« une trace n'est un souvenir qu'à condition d'être reprise, interprétée, parfois contestée par une conscience » et que « l'accumulation, à elle seule, n'y suffit pas » : conserver ne suffit donc pas. Il refuse en revanche de généraliser : « Il ne s'ensuit pas […] que toute conservation soit suspecte. » L'expression « à condition de » pose une condition nécessaire, pas suffisante : interpréter une trace ne garantit pas qu'elle devienne un souvenir. Enfin, la conclusion écarte explicitement l'idée d'une perte de mémoire : « ce n'est donc pas notre capacité à retenir » que le numérique menace.",
            ],
            [
                'niveau' => 'C2',
                'sous_niveau' => 'bas',
                'categorie' => 'Monde du travail',
                'enonce' => 'Que doit comprendre M. Côté à la lecture de cette lettre ?',
                'support' => "Montréal, le 3 février 2026\nPAR COURRIER RECOMMANDÉ\nMonsieur Jean-François Côté\nRénovations Côté inc.\nObjet : Mise en demeure – Contrat de rénovation du 14 juin 2025\nMonsieur,\nNous agissons pour le compte de Madame Hélène Bouchard, qui a retenu vos services le 14 juin 2025 pour la réfection de la toiture de sa résidence, située à Laval, moyennant la somme de 18 500 $, taxes incluses, dont 12 000 $ vous ont été versés à titre d'acompte.\nOr, en dépit de l'engagement pris au contrat de terminer les travaux au plus tard le 31 août 2025, ceux-ci demeurent inachevés à ce jour. Malgré les nombreux rappels de notre cliente, notamment les 15 septembre et 20 octobre 2025, vous n'avez fourni aucune date de reprise des travaux. De plus, des infiltrations d'eau ont causé des dommages au plafond du salon, constatés le 12 janvier dernier par un expert en bâtiment. Selon son rapport, la membrane d'étanchéité posée à l'automne n'a pas été fixée conformément aux règles de l'art.\nEn conséquence, nous vous mettons en demeure de terminer les travaux dans un délai de quinze (15) jours suivant la réception de la présente ou, à défaut, de rembourser à notre cliente la somme de 12 000 $ dans le même délai. À défaut de vous conformer à l'une ou l'autre de ces obligations, notre cliente se réserve le droit d'intenter, sans autre avis ni délai, tout recours approprié, notamment en dommages et intérêts, pour les préjudices subis.\nVeuillez agir en conséquence et recevoir, Monsieur, nos salutations distinguées.\nMe Caroline Lefebvre, avocate",
                'choix' => ['Un recours en dommages et intérêts a déjà été intenté contre lui.', 'Il a quinze jours à partir du 3 février pour finir les travaux.', 'Il évitera tout recours en payant les réparations du plafond du salon.', "Il risque un recours s'il ne remplit aucune des deux obligations."],
                'bonne_reponse' => 3,
                'feedback' => 'Impressionnant, tu as lu cette lettre comme un juriste !',
                'explication' => "La lettre laisse deux possibilités : « terminer les travaux » ou « rembourser à notre cliente la somme de 12 000 $ ». Elle précise : « À défaut de vous conformer à l'une ou l'autre de ces obligations, notre cliente se réserve le droit d'intenter […] tout recours approprié. » Le recours n'est donc qu'une menace : aucun recours n'a encore été intenté, et il suffit de respecter l'une des deux obligations pour l'écarter. Le délai de quinze jours court à partir de la « réception de la présente », et non de la date de la lettre. Enfin, payer les réparations du plafond ne fait pas partie des deux obligations : ces dommages pourraient au contraire être réclamés lors d'un recours.",
            ],
            [
                'niveau' => 'C2',
                'sous_niveau' => 'moyen',
                'categorie' => 'Monde du travail',
                'enonce' => "Quelle est la position réelle de l'auteur ?",
                'support' => "Éloge de la réunion\nQu'on se le dise : la réunion est la plus belle invention de l'entreprise moderne. Elle seule permet à douze personnes de ne pas travailler en même temps, dans la même pièce, en toute transparence. Qui oserait encore prétendre qu'elle est improductive ? Elle produit, au contraire, énormément : des comptes rendus, des points d'étape et, surtout, d'autres réunions, qu'il faudra bien préparer lors de réunions préparatoires.\nÀ Bruxelles, où je travaille, cet art a atteint sa perfection. Il n'est pas rare qu'une « réunion de cadrage » débouche sur la création d'un « groupe de travail » chargé de définir le « périmètre » d'une future « task force ». Le vocabulaire y contribue : on n'y parle pas, on « partage » ; on n'y décide pas, on « acte » ; on n'y renonce pas, on « met en attente ». Chacun en ressort avec le sentiment grisant d'avoir avancé, sans que personne soit capable de dire dans quelle direction. C'est là tout le génie du dispositif : la décision, cette chose brutale et compromettante, s'y dissout avec élégance dans le consensus.\nOn me dira que les participants s'y ennuient, qu'ils lisent leurs courriels sous la table et rattrapent le soir le travail qu'ils n'ont pu faire le jour. Mauvais esprit ! C'est oublier la fonction sociale de l'exercice : où, sinon en réunion, pourrait-on admirer en direct la patience infinie de ceux qui écoutent et l'assurance inébranlable de ceux qui parlent ? Certains esprits chagrins proposent même de limiter les réunions à trente minutes, voire de les tenir debout. Quelle brutalité !\nJe propose donc, pour conclure, que l'on organise dès la rentrée une grande réunion sur l'excès de réunions. J'y serai, bien sûr. J'ai déjà bloqué l'après-midi.",
                'choix' => ['Les réunions sont indispensables, car elles favorisent le consensus.', 'Les réunions sont trop nombreuses et servent surtout à éviter de décider.', "Les participants qui s'ennuient en réunion font preuve de mauvais esprit.", 'Il faudrait organiser une grande réunion pour réduire leur nombre.'],
                'bonne_reponse' => 1,
                'feedback' => "Bravo, tu as su lire l'ironie au second degré !",
                'explication' => "Le texte est ironique : il fait semblant de louer les réunions pour mieux les critiquer. Quand l'auteur écrit qu'elles permettent « de ne pas travailler en même temps » ou que la décision « s'y dissout avec élégance dans le consensus », il dénonce leur nombre et leur fonction réelle : éviter de décider. Les autres réponses prennent le texte au premier degré : l'éloge du consensus, le « Mauvais esprit ! » adressé aux participants qui s'ennuient, et la proposition finale d'une « grande réunion sur l'excès de réunions », qui est une absurdité volontaire, confirmée par la chute : « J'ai déjà bloqué l'après-midi. »",
            ],
            [
                'niveau' => 'C2',
                'sous_niveau' => 'moyen',
                'categorie' => 'Textes argumentatifs',
                'enonce' => "Pourquoi l'auteur met-il entre guillemets des expressions comme « optimisation du réseau » ?",
                'support' => "Petit lexique à l'usage des usagers\nIl fut un temps où, lorsqu'on fermait un bureau de poste, on disait qu'on fermait un bureau de poste. Cette brutalité appartient au passé. On procède désormais à une « optimisation du réseau », dont chacun est invité à saluer la « modernité ». Le guichet où Madame Rochat, 83 ans, retirait sa rente depuis quarante ans n'a pas disparu : il a été « transformé en point de service partenaire », c'est-à-dire en étagère au fond de l'épicerie du village, ouverte trois après-midi par semaine quand l'épicière n'est pas malade. Le guichetier, lui, a été « redéployé ».\nVous n'êtes d'ailleurs plus un usager, mais un « client », ce qui est flatteur, et vous n'avez plus de problème, mais une « situation », ce qui est rassurant. Si votre courrier arrive avec trois jours de retard, c'est que les délais ont été « harmonisés ». Et si, par malheur, vous vous plaignez, votre réclamation sera « prise en compte », formule qui, comme chacun sait, dispense de la prendre en considération. Si vous ne comprenez pas le nouveau formulaire en ligne, c'est que vous n'avez pas encore « pris le virage numérique », ce qui, à 83 ans, relève manifestement de la mauvaise volonté. Le formulaire compte onze pages et propose un « parcours simplifié » en sept étapes ; Madame Rochat s'est arrêtée à la deuxième.\nLoin de moi l'idée de nier que les habitudes changent, ni que le courrier diminue. Mais il y a quelque chose d'inquiétant dans une langue qui sert moins à désigner les choses qu'à empêcher de les voir. Le jour où l'on appellera « libération d'espace » la démolition d'une école, nous aurons au moins la consolation de savoir que ce n'était pas une fermeture.",
                'choix' => ["Pour se distancer de ces formules et en dénoncer l'hypocrisie", "Pour signaler qu'il recopie mot pour mot un rapport officiel de la poste", 'Pour souligner la modernité réelle des nouveaux services', 'Pour rapporter les propres mots de Madame Rochat'],
                'bonne_reponse' => 0,
                'feedback' => 'Excellent, tu as repéré les guillemets de distance !',
                'explication' => "Les guillemets signalent des mots empruntés au langage de l'administration, que l'auteur reprend pour s'en moquer. Chaque expression est aussitôt traduite en termes crus : le « point de service partenaire » n'est qu'une « étagère au fond de l'épicerie du village ». L'auteur conclut qu'il y a « quelque chose d'inquiétant dans une langue qui sert moins à désigner les choses qu'à empêcher de les voir ». Il ne cite aucun rapport précis. Il ne croit pas non plus à la « modernité » des services, qu'il met lui-même entre guillemets. Enfin, ces mots ne sont pas ceux de Madame Rochat, qui subit ces changements.",
            ],
            [
                'niveau' => 'C2',
                'sous_niveau' => 'haut',
                'categorie' => 'Textes littéraires',
                'enonce' => 'Que comprend-on de la réaction du narrateur à la fin du texte ?',
                'support' => "Il n'est pas de maison qu'on quitte tout à fait. Celle de Saint-Aubin, où mon père passa les vingt dernières années de sa vie, m'avait toujours paru trop grande pour lui, et je crois qu'il l'avait voulue ainsi, comme on garde une place à table pour quelqu'un qui ne viendra pas. Ma mère était partie un matin d'octobre ; il ne l'avait jamais reprise, ni remplacée, ni même, que je sache, nommée devant moi. Les photographies de ma mère avaient disparu des murs ; seules demeuraient, plus claires sur le papier peint, les traces rectangulaires des cadres.\nNous nous voyions peu. Il eût fallu, pour que nous fussions proches, que l'un de nous deux fît le premier pas, et nous avions l'un et l'autre, en cette matière comme en d'autres, une patience infinie. Nos lettres, rares, parlaient du temps qu'il faisait, des pommiers, des cours de la Bourse. Il les signait « Ton père », comme on appose un cachet. Je n'y cherchais rien ; il n'y mettait rien, ou si bien caché que je ne sus le trouver.\nC'est en vidant son bureau que je découvris, rangées par année dans une boîte à chaussures, toutes les coupures de presse où mon nom avait paru, jusqu'au plus insignifiant compte rendu de colloque. Certaines étaient soulignées au crayon. Au dos de l'une d'elles, de sa petite écriture penchée, il avait noté : « Il a la voix de sa mère. » Il m'avait entendu une fois à la radio, et ne m'en avait jamais parlé.\nJe ne dirai pas que cette découverte me laissa indifférent. Je restai simplement assis sur le parquet jusqu'à la nuit, sans allumer, à relire des articles que je connaissais par cœur et que, pour la première fois, je lisais.",
                'choix' => ['Il reste froid, car ces articles ne lui apprennent rien de nouveau.', 'Il en veut à son père de ne lui avoir jamais parlé de la radio.', 'Il découvre que son père lui reprochait de ressembler à sa mère.', "Il est bouleversé de découvrir l'attention secrète de son père."],
                'bonne_reponse' => 3,
                'feedback' => 'Magnifique lecture, tu as entendu tout ce que la litote tait !',
                'explication' => "« Je ne dirai pas que cette découverte me laissa indifférent » est une litote : en disant peu, le narrateur fait entendre beaucoup. Il reste assis « jusqu'à la nuit, sans allumer » : il est bouleversé de découvrir que son père, si silencieux, suivait en secret chacun de ses articles. Il connaissait ces textes « par cœur », mais « pour la première fois », il les lisait avec les yeux de son père : ils lui apprennent donc quelque chose. Rien n'indique de rancune envers son père. Enfin, la note « Il a la voix de sa mère » n'est pas un reproche : gardée avec les articles soulignés, elle trahit une tendresse que le père n'avait jamais exprimée.",
            ],
            [
                'niveau' => 'C2',
                'sous_niveau' => 'haut',
                'categorie' => 'Textes argumentatifs',
                'enonce' => "Quel rôle joue le premier paragraphe dans l'argumentation ?",
                'support' => "La transparence a tout pour plaire. Elle promet des institutions sans recoins, des décisions sans coulisses, des dirigeants qui n'auraient plus rien à cacher parce qu'ils n'auraient plus nulle part où le cacher. Qui pourrait s'opposer à ce que le citoyen voie ce qui se fait en son nom ? L'opacité a toujours servi les puissants ; la lumière, dit-on, est le meilleur des désinfectants. Chaque scandale révélé semble lui donner raison.\nTout cela est exact, et c'est bien ce qui rend l'idée si redoutable. Car une exigence qui ne rencontre aucune limite cesse d'être une vertu pour devenir un régime. À vouloir tout exposer, on n'obtient pas des délibérations plus honnêtes, mais des délibérations ailleurs : là où l'on peut encore hésiter, se contredire, essayer une idée sans être sommé d'en répondre sur-le-champ. Une assemblée filmée en permanence ne délibère plus, elle se met en scène ; ce qu'on y gagne en visibilité, on le perd en pensée. Les négociations les plus délicates, celles qui supposent des concessions, se déplacent alors dans les couloirs, loin des caméras et, par conséquent, de tout contrôle. Le soupçon, lui, ne disparaît pas : il change simplement d'adresse.\nIl ne s'agit pas, pour autant, de réhabiliter le secret. Il s'agit de rappeler qu'une démocratie a besoin de moments de publicité et de moments de retrait, et que la frontière entre les deux doit être elle-même publique, discutée, révisable. Encore faut-il que cette frontière ne soit pas tracée par ceux-là mêmes qu'elle est censée protéger. La transparence n'est pas le contraire du mensonge ; elle n'en est souvent que la version la plus sophistiquée, celle qui montre tout pour que l'on ne voie rien. Réclamer la lumière partout, c'est oublier qu'elle aussi projette des ombres.",
                'choix' => ["Il pose la thèse de l'auteur, favorable à une transparence sans limites.", "Il sert à réfuter d'avance ceux qui veulent réhabiliter le secret.", "Il présente une idée séduisante dont l'auteur montrera les limites.", "Il donne l'exemple concret d'une assemblée filmée en permanence."],
                'bonne_reponse' => 2,
                'feedback' => 'Bravo, tu as déjoué une concession stratégique, du vrai niveau C2 !',
                'explication' => "Le premier paragraphe fait l'éloge de la transparence, mais l'auteur s'en détache dès la phrase suivante : « Tout cela est exact, et c'est bien ce qui rend l'idée si redoutable. » Il reconnaît la part de vérité de cette idée pour mieux en montrer les limites : « une exigence qui ne rencontre aucune limite cesse d'être une vertu ». Ce n'est donc pas la thèse qu'il défend, puisqu'il conclut que la lumière « projette des ombres ». Le refus de « réhabiliter le secret » n'apparaît que dans le dernier paragraphe, et l'auteur ne réfute personne : il écarte lui-même cette idée. Enfin, l'exemple de l'« assemblée filmée en permanence » se trouve dans le deuxième paragraphe.",
            ],
        ]);
    }

    /** @param  list<array<string, mixed>>  $questions */
    private function questions(array $questions): void
    {
        $epreuve = Epreuve::where('code', 'ce')->firstOrFail();
        $epreuve->questions()->whereNotNull('niveau')->delete();

        foreach ($questions as $ordre => $question) {
            $epreuve->questions()->create($question + ['ordre' => $ordre]);
        }
    }
}
